In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import confusion_matrix

In [ ]:
train = pd.read_csv('fashion_train.csv', header = None)
test = pd.read_csv('fashion_test.csv', header = None)

In [ ]:
train=train.dropna(0)
test=test.dropna(0)
pixels = train.iloc[:,1:785]
print(pixels)

       1    2    3    4    5    6    7    ...  778  779  780  781  782  783  784
0        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1        0    0    0    0    0    1    0  ...   76    0    0    0    0    0    0
2        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59996    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59997    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59998    0    0    0    0    0    0    0  ...    5    0    1    0    0    0    0
59999    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[60000 rows x 784 columns]


K = 1

In [ ]:
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier(n_neighbors=1,algorithm='kd_tree')
clf.fit(pixels,train[0])

predict=clf.predict(test.iloc[:,1:785])


In [ ]:
cm=confusion_matrix(predict,test[0])
print(cm)

[[800   7  15  35   5   0 160   0   5   0]
 [  2 975   2   9   2   0   1   0   1   0]
 [ 20   2 782  14 127   0 117   0   9   0]
 [ 26   8  10 850  34   0  27   0   3   0]
 [  5   4  97  42 734   0  69   0   2   0]
 [  0   0   0   0   0 863   0   5   0   2]
 [142   3  94  48  97   2 619   0  17   0]
 [  1   0   0   0   0  68   0 949   4  30]
 [  4   1   0   2   1   1   7   0 958   1]
 [  0   0   0   0   0  66   0  46   1 967]]


K = 11

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(predict,test[0]))

0.8497


In [ ]:
clf=neighbors.KNeighborsClassifier(n_neighbors=11,algorithm='kd_tree')
clf.fit(pixels,train[0])

predict=clf.predict(test.iloc[:,1:785])

In [ ]:
cm=confusion_matrix(predict,test[0])
print(cm)

[[860  10  22  35   1   1 178   0   1   0]
 [  0 962   2   4   0   0   0   0   1   0]
 [ 18   6 807  14 117   0 135   0  15   0]
 [ 18  14   6 864  27   1  22   0   2   0]
 [  5   4  88  41 758   0  75   0  10   0]
 [  0   0   0   0   0 793   0   2   0   0]
 [ 90   4  74  41  96   5 576   0  15   1]
 [  1   0   0   0   0 111   0 960   6  32]
 [  8   0   1   1   1   2  14   0 948   0]
 [  0   0   0   0   0  87   0  38   2 967]]


In [ ]:
print(accuracy_score(predict,test[0]))

0.8495


K = 21

In [ ]:
from sklearn import neighbors
clf=neighbors.KNeighborsClassifier(n_neighbors=21,algorithm='kd_tree')
clf.fit(pixels,train[0])

KNeighborsClassifier(algorithm='kd_tree', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=21, p=2,
                     weights='uniform')

In [ ]:
predict=clf.predict(test.iloc[:,1:785])


In [ ]:
cm=confusion_matrix(predict,test[0])
print(cm)

[[860   9  20  31   0   1 188   0   1   0]
 [  0 952   1   5   0   0   1   0   1   0]
 [ 18   9 795  15 107   0 141   0  21   0]
 [ 19  19   6 864  27   2  21   0   3   0]
 [  8   4  82  41 752   0  75   0   8   0]
 [  0   0   0   0   0 772   0   1   0   0]
 [ 83   7  93  41 110   7 559   0  16   2]
 [  1   0   0   0   0 129   0 951   8  36]
 [ 11   0   3   3   4   2  15   0 940   0]
 [  0   0   0   0   0  87   0  48   2 962]]


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(predict,test[0]))

0.8407
